### ISSUE TITLE
KeyError: 'user-agent'

### ISSUE THREAD

**Issue by zubairbaqai** [tom-draper/api-analytics#26]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/usr/local/lib/python3.10/dist-packages/api_analytics/fastapi.py", line 25, in dispatch
    'user_agent': request.headers['user-agent'],
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 568, in __getitem__
    raise KeyError(key)
KeyError: 'user-agent'

i tried integrating this on my FastAPI, and this is what i am getting when utilizing this on AWS environment.

**Comment by tom-draper** [comment]
Thanks for letting me know, updating the `fastapi-analytics` package to `1.1.5` should fix the issue!
