### ISSUE TITLE
TypeError: Mappers.get_hostname() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by saurabhlalsaxena** [tom-draper/api-analytics#48]
[2024-10-08 16:25:57,279] ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 904, in finalize_request
    response = self.process_response(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1281, in process_response
    response = self.ensure_sync(func)(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/api_analytics/flask.py", line 35, in on_finish
    "hostname": config.get_hostname(request, config),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Mappers.get_hostname() takes 1 positional argument but 2 were given
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 904, in finalize_request
    response = self.process_response(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1281, in process_response
    response = self.ensure_sync(func)(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/api_analytics/flask.py", line 35, in on_finish
    "hostname": config.get_hostname(request, config),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Mappers.get_hostname() takes 1 positional argument but 2 were given

**Comment by tom-draper** [comment]
Thanks for raising this. Tests should have caught this but were configured incorrectly. Patch is available now if you upgrade to `api_analytics==1.2.5`
